name: Build via CMake

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-hiredis:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        configration: [release, debug]
        build_shared_libs: [shared, static]

    steps:
      - uses: microsoft/setup-msbuild@main
      - uses: actions/checkout@v4
      
      - name: Run CMake
        run: |
          if ( "${{ matrix.build_shared_libs }}" -eq "shared" ) {
            cmake -Wno-dev CMakeLists.txt
          } else {
            cmake -Wno-dev CMakeLists.txt -DBUILD_SHARED_LIBS=OFF
          }
          
      - name: Build Hiredis
        id: build
        run: |
          if ( "${{ matrix.configration }}" -eq "release" ) {
            MSBuild hiredis.vcxproj /p:Configuration=Release
          } else {
            MSBuild hiredis.vcxproj /p:Configuration=Debug
          }

      - name: Prepare Upload
        continue-on-error: true
        if: steps.build.outcome == 'success'
        run: |
          mkdir ${{ matrix.configration }}-${{ matrix.build_shared_libs }}
          if ( "${{ matrix.configration }}" -eq "release" ) {
            Copy-Item .\Release\* .\${{ matrix.configration }}-${{ matrix.build_shared_libs }}\ -Force
            Remove-item .\Release -Force -Recurse
          } else {
            Copy-Item .\Debug\* .\${{ matrix.configration }}-${{ matrix.build_shared_libs }}\ -Force
            Remove-item .\Debug -Force -Recurse
          }

      - name: Release Hiredis
        continue-on-error: true
        if: steps.build.outcome == 'success'
        uses: ncipollo/release-action@main
        with:
          name: windows-hiredis-${{ matrix.configration }}-${{ matrix.build_shared_libs }}
          tag: windows-${{ matrix.configration }}-${{ matrix.build_shared_libs }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: "${{ github.workspace }}\\${{ matrix.configration }}-${{ matrix.build_shared_libs }}\\*.*"
          
      - name: Upload Artifacts
        continue-on-error: true
        if: steps.build.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: "windows-hiredis-${{ matrix.configration }}-${{ matrix.build_shared_libs }}"
          path:  |
            ${{ github.workspace }}
